name: BowlerProtoRelease

on:
  repository_dispatch:
    types: [bowler-proto-release]

jobs:
  BowlerProtoRelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
          ssh-key: ${{ secrets.BOWLERBOT_SSH_KEY }}

      - name: Parse this tag
        id: parse-tag
        run: |
          THIS_TAG="$(grep 'projectVersion' 'buildSrc/src/main/kotlin/Versions.kt' | awk '{ print $5 }' | tr -d \")"
          echo "::set-output name=tag::$(echo $THIS_TAG)"

      - name: Set bowler-proto to the newly released version
        env:
          THIS_TAG: ${{ steps.parse-tag.outputs.tag }}
          NEW_TAG: ${{ github.event.client_payload.ref }}
        run: |
          cd bowler-proto
          git checkout ${{ github.event.client_payload.sha }}
          cd ..
          sed -i "/projectVersion = \"$THIS_TAG\"/ s/$THIS_TAG/$NEW_TAG/" buildSrc/src/main/kotlin/Versions.kt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.BOWLERBOT_PAT }}
          commit-message:  ${{ format('Bump bowler-proto to {0}.', github.event.client_payload.ref) }}
          title: ${{ format('[AUTO] Bump bowler-proto to {0}.', github.event.client_payload.ref) }}
          body: ${{ format('Updating bowler-proto to {0}.', github.event.client_payload.ref) }}
          branch: ${{ format('update-bowler-proto-{0}', github.event.client_payload.ref) }}
