name: BowlerProtoRelease

on:
  repository_dispatch:
    types: [bowler-proto-release]

jobs:
  BowlerProtoRelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
          ssh-key: ${{ secrets.BOWLERBOT_SSH_KEY }}

      - name: Set bowler-proto to the newly released version
        run: |
          cd bowler-proto && git checkout ${{ github.event.client_payload.release }} && cd ..

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump bowler-proto"
          title: "[AUTO] Bump bowler-proto"
          body: ${{ format('Updating bowler-proto to {0}.', github.event.client_payload.release) }}
          branch: ${{ format('update-bowler-proto-{0}', github.event.client_payload.release) }}
